template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "chip1241"
__REPO__ = "lang-ciw"
__UND2C__ = "ciw"
__UNDEFINED__ = "Chippewa"
__UND__ = "ciw"
