template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "chip1241"
__REPO__ = "lang-ciw"
__UND2C__ = "ciw"
__UNDEFINED__ = "Chippewa"
__UND__ = "ciw"
